[Needs fixing] Doesn't work for me yet.
The full terminal session going through this is at https://pastebin.com/7W7wCJv3 and https://pastebin.com/N1xwUFTx, with the end of the latter showing the failure of `hc test`:

```zsh
$ hc test
Packaging files for testing to file: "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Finished release [optimized] target(s) in 0.09s
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Finished release [optimized] target(s) in 0.09s
Created DNA package file at "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
DNA hash: QmS2FN9ctXQbV7qKkTr4paBJveytPPos8PqQTFxELSjz6R
Installing node_modules
> npm install --silent
[@holochain/holochain-nodejs] Success: "/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/bin-package/index.node" is installed via remote
added 156 packages from 111 contributors and audited 264 packages in 18.691s
found 0 vulnerabilities

Running tests in test/index.js
> node test/index.js
TAP version 13
# description of example test
Reading DNA from ./dist/holochain-rust-todo.dna.json
Failed to load instance alice from storage: ErrorGeneric("State could not be loaded due to NoneError")
Initializing new chain...
Starting instance "alice"...
Exception occurred while calling zome function:  unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
Stopping instance "alice"...
not ok 1 unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
  ---
    operator: fail
    at: Test.Scenario._tape (/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/index.js:195:23)
    stack: |-
      Error: unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
          at Test.assert [as _assert] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:77:32)
          at Test.Scenario._tape (/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/index.js:195:23)
          at <anonymous>
          at runMicrotasksCallback (internal/process/next_tick.js:122:5)
          at _combinedTickCallback (internal/process/next_tick.js:132:7)
          at process._tickCallback (internal/process/next_tick.js:181:9)
  ...

1..1
# tests 1
# pass  0
# fail  1

Error: command node test/index.js was not successful
```